<?php

declare(strict_types=1);

namespace App\Infrastructure\Assurance;

use LogicException;

/** Turkish prose only; measurements, states and evidence stay in the measured builder. */
final class TurkishAssuranceContent
{
    private const TEXT = [
        'Trust centre' => 'Güven merkezi',
        'What this service can show you before you buy: where your data is kept, who else touches it, what is committed about availability, how the backup drill is measured, and what is not measured at all.' => 'Bu hizmetin satın almadan önce gösterebildikleri: verilerinizin nerede tutulduğu, başka kimlerin işlediği, kullanılabilirlik taahhütleri, yedekleme tatbikatının nasıl ölçüldüğü ve hiç ölçülmeyenler.',
        'Accessibility statement' => 'Erişilebilirlik beyanı',
        'What is measured about the accessibility of this service and by which gate, what is known to be wrong, what has not been measured at all, and how to tell us about something we missed.' => 'Bu hizmetin erişilebilirliği hakkında neyin hangi kontrolle ölçüldüğü, bilinen kusurlar, hiç ölçülmeyenler ve gözden kaçırdığımız bir sorunu nasıl bildirebileceğiniz.',
        'How to read this page' => 'Bu sayfa nasıl okunmalı?',
        'Every answer on this page is drawn from what this installation is actually running, or names the command in the source code that produces it. Nothing on it is a summary somebody typed once and stopped maintaining: the subprocessor list, the hosting row and the service level figures are read again each time you open the page.' => 'Bu sayfadaki her yanıt, bu kurulumda gerçekten çalışanlardan türetilir veya yanıtı üreten kaynak kod komutunu adlandırır. Buradaki hiçbir şey, bir kez yazılıp bakımı bırakılmış bir özet değildir: alt işleyen listesi, barındırma satırı ve hizmet seviyesi değerleri sayfayı her açtığınızda yeniden okunur.',
        'Where something has not been measured, the page says that in those words. It does not soften the gap with a hedging adjective, because a hedged gap is how an unmeasured thing comes to be read as a measured one.' => 'Bir şey ölçülmemişse sayfa bunu açıkça söyler. Eksikliği ihtiyatlı bir sıfatla yumuşatmaz; çünkü yumuşatılan bir eksiklik, ölçülmemiş bir şeyin ölçülmüş gibi okunmasına yol açar.',
        'This page is not a contract. The contracts are the Terms of Service, the Data Processing Agreement and the Service Level Terms, each of which has its own version number and effective date. Where this page and one of those differ, the contract is what applies.' => 'Bu sayfa bir sözleşme değildir. Sözleşmeler; her birinin kendi sürüm numarası ve yürürlük tarihi bulunan Hizmet Koşulları, Veri İşleme Sözleşmesi ve Hizmet Seviyesi Koşullarıdır. Bu sayfa ile bunlardan biri arasında fark varsa sözleşme geçerlidir.',
        'Certificates, audit reports and badges' => 'Sertifikalar, denetim raporları ve rozetler',
        'A third-party security certificate or audit report' => 'Üçüncü taraf güvenlik sertifikası veya denetim raporu',
        'This service holds none. There is no ISO 27001 certificate, no SOC 2 report, no PCI DSS attestation and no equivalent third-party audit, and no badge for one is shown anywhere on this site. If your procurement process requires one, that is a question to settle before you subscribe rather than after.' => 'Bu hizmet bunların hiçbirine sahip değildir. ISO 27001 sertifikası, SOC 2 raporu, PCI DSS uygunluk belgesi veya eşdeğer bir üçüncü taraf denetimi yoktur; sitede bunlara ilişkin bir rozet de gösterilmez. Satın alma süreciniz bunlardan birini gerektiriyorsa bu konu abonelikten sonra değil, önce netleştirilmelidir.',
        'Public endpoint monitoring' => 'Herkese açık uç nokta izlemesi',
        'Public endpoint checks are published at https://zabuno.github.io/status/. Five endpoints have been monitored since 2026-09-08; the figures describe only the recorded period and those endpoint checks. They do not measure complete user journeys or create a contractual availability guarantee. The service level section below identifies the commercial values still missing.' => 'Herkese açık uç nokta kontrolleri https://zabuno.github.io/status/ adresinde yayımlanır. Beş uç nokta 2026-09-08 tarihinden beri izlenmektedir; rakamlar yalnızca kaydedilen dönemi ve bu uç nokta kontrollerini kapsar. Tam kullanıcı yolculuklarını ölçmez ve sözleşmesel kullanılabilirlik garantisi oluşturmaz. Aşağıdaki hizmet seviyesi bölümü eksik ticari değerleri belirtir.',
        'Where your data is kept' => 'Verileriniz nerede tutuluyor?',
        'Hosting location' => 'Barındırma konumu',
        'The hosting row could not be read from this installation\'s configuration when this page was drawn, so this page does not state where the data is kept. Ask, and it will be answered in writing.' => 'Sayfa hazırlanırken barındırma satırı bu kurulumun yapılandırmasından okunamadı; bu nedenle sayfa verilerin nerede tutulduğunu belirtmiyor. Sorarsanız yazılı olarak yanıtlanır.',
        'This is the one processing location this service can measure: the server the application, the database and the uploaded files actually live on. Where a third party keeps the data it receives is set out in that party\'s own terms and is not measured here — the subprocessor list below says so on every row rather than guessing.' => 'Hizmetin ölçebildiği tek işleme konumu budur: uygulamanın, veritabanının ve yüklenen dosyaların gerçekten bulunduğu sunucu. Üçüncü tarafın aldığı verileri nerede tuttuğu, kendi koşullarında belirtilir ve burada ölçülmez. Aşağıdaki alt işleyen listesi tahmin yürütmek yerine bunu her satırda belirtir.',
        'Hosting' => 'Barındırma',
        'The hosting provider or location has not been entered for this installation, so this page names neither. It reads them from the deployment\'s own configuration and shows what is there, which today is nothing.' => 'Bu kurulum için barındırma sağlayıcısı veya konumu girilmediğinden sayfa bunların adını vermiyor. Bu bilgileri dağıtımın kendi yapılandırmasından okur ve orada ne varsa gösterir; bugün orada hiçbir bilgi yoktur.',
        'The list below is not typed by hand. It is generated from the credentials and the measurement settings this installation is running when you open the page, so a provider with no active credential is not listed — because it is not processing anything today. Adding a provider to the software without describing it here breaks the build.' => 'Aşağıdaki liste elle yazılmaz. Sayfayı açtığınız anda kurulumda kullanılan kimlik bilgileri ve ölçüm ayarlarından üretilir. Etkin kimlik bilgisi olmayan sağlayıcı listelenmez; çünkü bugün veri işlemiyordur. Yazılıma bir sağlayıcı eklenip burada açıklanmazsa derleme başarısız olur.',
        'The credential store could not be read while this page was drawn, so the list below may be incomplete. That is stated rather than hidden: an empty list and an unread list are not the same sentence, and treating them as one would be the most expensive mistake this page could make.' => 'Sayfa hazırlanırken kimlik bilgisi deposu okunamadı; bu nedenle aşağıdaki liste eksik olabilir. Bu durum gizlenmez: boş liste ile okunamamış liste aynı şey değildir. İkisini bir saymak bu sayfanın yapabileceği en pahalı hata olurdu.',
        'The measurement container in that list runs in the visitor\'s browser and only after the visitor allows measurement in the cookie choice. This service\'s own servers do not send visitor data to it.' => 'Listedeki ölçüm kapsayıcısı ziyaretçinin tarayıcısında ve yalnızca ziyaretçi çerez tercihinde ölçüme izin verdikten sonra çalışır. Bu hizmetin kendi sunucuları ona ziyaretçi verisi göndermez.',
        'The same list, with the contractual wording around it, is in the Data Processing Agreement at /data-processing.' => 'Aynı liste, onu çevreleyen sözleşme metniyle birlikte /data-processing adresindeki Veri İşleme Sözleşmesinde yer alır.',
        'Who else touches your data' => 'Verilerinizi başka kimler işliyor?',
        'Availability target' => 'Kullanılabilirlik hedefi',
        'No availability percentage is committed today. Public endpoint monitoring is available at https://zabuno.github.io/status/, but its recorded observations are not a contractual SLA or a measurement of complete user journeys. Four commercial values must be decided by the operator with legal advice before an availability commitment is stated. Still to be decided: ' => 'Bugün kullanılabilirlik yüzdesi taahhüt edilmiyor. Herkese açık uç nokta izlemesi https://zabuno.github.io/status/ adresinde bulunur; ancak kaydedilen gözlemler sözleşmesel SLA veya tam kullanıcı yolculuklarının ölçümü değildir. Kullanılabilirlik taahhüdü belirtilmeden önce dört ticari değerin işletmeci tarafından hukuki danışmanlıkla kararlaştırılması gerekir. Hâlâ karar bekleyenler: ',
        'Incident notification' => 'Olay bildirimi',
        'No notification time has been entered for this installation (incident_notification_minutes), so this page states none. Public endpoint observations can be checked at https://zabuno.github.io/status/; they do not establish a customer notification deadline.' => 'Bu kurulum için bildirim süresi (incident_notification_minutes) girilmediğinden bu sayfa süre belirtmez. Herkese açık uç nokta gözlemleri https://zabuno.github.io/status/ adresinden kontrol edilebilir; bunlar müşteriye bildirim için son süre belirlemez.',
        'Service credit when the target is missed' => 'Hedef tutturulamadığında hizmet kredisi',
        'Service level' => 'Hizmet seviyesi',
        'The full text, including what is excluded and how availability would be measured, is in the Service Level Terms at /sla. What follows is the same set of facts, in short.' => 'İstisnalar ve kullanılabilirliğin nasıl ölçüleceği dahil tam metin /sla adresindeki Hizmet Seviyesi Koşullarında yer alır. Aşağıdakiler aynı olguların kısa özetidir.',
        'Backups: how the drill is measured' => 'Yedekler: tatbikat nasıl ölçülüyor?',
        'The operator\'s own rule is that an untested backup is not a backup, so what this service has is not a backup setting but a drill: a command that takes a backup, restores it somewhere isolated, compares what came back with what went in, and records the result.' => 'İşletmecinin kendi kuralı, denenmemiş bir yedeğin yedek sayılmamasıdır. Bu nedenle hizmetin sunduğu yalnızca bir yedekleme ayarı değil, bir tatbikattır: yedek alan, onu yalıtılmış bir yere geri yükleyen, geri geleni kaynağıyla karşılaştıran ve sonucu kaydeden bir komut.',
        'For the database, the drill opens a repeatable-read transaction, exports a snapshot, counts the rows and digests their content from that snapshot, then archives the same snapshot. It restores the archive into a throwaway database created for the run, compares table list, row counts and content digest against the source, then drops the copy and deletes the archive. Nothing is ever written to the source database.' => 'Veritabanı için tatbikat, tekrarlanabilir okuma düzeyinde bir işlem açar, anlık görüntüyü dışa aktarır, bu görüntüdeki satırları sayar ve içerik özetlerini hesaplar; ardından aynı görüntüyü arşivler. Arşivi koşu için oluşturulmuş geçici bir veritabanına geri yükler, tablo listesini, satır sayılarını ve içerik özetini kaynakla karşılaştırır; sonra kopyayı ve arşivi siler. Kaynak veritabanına hiçbir zaman yazılmaz.',
        'For uploaded files, the drill archives the media root, unpacks it somewhere isolated and compares the files that came back with the files that went in. A corrupted archive fails the drill rather than passing it quietly.' => 'Yüklenen dosyalar için tatbikat medya kökünü arşivler, yalıtılmış bir yerde açar ve geri gelen dosyaları kaynak dosyalarla karşılaştırır. Bozuk arşiv sessizce başarılı sayılmaz; tatbikatı başarısız kılar.',
        'A drill has three outcomes and all three are recorded. "Passed" means the comparison held. "Failed" means a step broke or the comparison did not hold. "Unknown" means the drill could not be attempted at all — the tool was missing, the client was older than the server, the source could not be read. "Unknown" is never reported as a pass, and the command does not exit successfully while claiming it.' => 'Tatbikatın üç sonucu vardır ve hepsi kaydedilir. “Başarılı”, karşılaştırmanın eşleştiği anlamına gelir. “Başarısız”, bir adımın bozulduğu veya karşılaştırmanın eşleşmediği anlamına gelir. “Bilinmiyor”, tatbikatın hiç denenemediği anlamına gelir: araç yoktur, istemci sunucudan eskidir veya kaynak okunamamıştır. “Bilinmiyor” hiçbir zaman başarı olarak raporlanmaz ve komut bu sonucu bildirirken başarı koduyla çıkmaz.',
        'The backup and restore drill' => 'Yedekleme ve geri yükleme tatbikatı',
        'One command runs both drills and appends one evidence record each, recording the driver, the row counts, the digest of what was backed up, the digest of what was restored, the archive size and the timings. It exits successfully only when every selected drill passed.' => 'Tek komut iki tatbikatı da çalıştırır ve her biri için bir kanıt kaydı ekler. Sürücüyü, satır sayılarını, yedeklenen ve geri yüklenen içeriğin özetlerini, arşiv boyutunu ve süreleri kaydeder. Yalnızca seçilen tatbikatların tamamı başarılı olduğunda başarı koduyla çıkar.',
        'A drill result for the installation you would be buying' => 'Satın alacağınız kuruluma ait tatbikat sonucu',
        'This page publishes no drill result. A drill writes its record into the installation it runs in, and this page does not read that record — a result printed here would be a snapshot of one moment, with no way for you to tell when it was taken. Ask for the latest record in writing and you will be told what it says, including if it says "unknown".' => 'Bu sayfa tatbikat sonucu yayımlamaz. Tatbikat, kaydını çalıştığı kuruluma yazar; bu sayfa o kaydı okumaz. Buraya basılan sonuç tek bir anın görüntüsü olur ve ne zaman alındığını anlayamazdınız. En son kaydı yazılı olarak isteyin; “bilinmiyor” diyorsa bu dahil, kaydın ne söylediği size bildirilir.',
        'Security evidence you can run yourself' => 'Kendiniz çalıştırabileceğiniz güvenlik kontrolleri',
        'This software is open source, so the checks below are not claims you have to take on trust: they are commands in the repository, and you can read what they do and run them against an installation of your own.' => 'Bu yazılım açık kaynaklıdır. Aşağıdaki kontroller güvenmenizi bekleyen iddialar değil, depodaki komutlardır. Ne yaptıklarını okuyabilir ve kendi kurulumunuzda çalıştırabilirsiniz.',
        'Tenant isolation' => 'Kiracı yalıtımı',
        'Runs the frozen tenant-isolation suite — the tests that check one workspace cannot read, list or act on another workspace\'s data — and appends one evidence record with the outcome. It exits unsuccessfully when the suite fails, so it cannot record a pass it did not get.' => 'Bir çalışma alanının başka bir alanın verilerini okuyamadığını, listeleyemediğini veya bunlar üzerinde işlem yapamadığını denetleyen dondurulmuş kiracı yalıtımı testlerini çalıştırır ve sonucu bir kanıt kaydına ekler. Testler başarısızsa başarısızlık koduyla çıkar; almadığı bir başarıyı kaydedemez.',
        'Host capability' => 'Sunucu yetenekleri',
        'Probes the server the software is installed on for the capabilities the product depends on, records one evidence row and prints the degradation plan — which features run in reduced form on that host and which do not run at all. A missing capability is reported as a planned degradation rather than as a failure, because a host that lacks one is a fact to state, not a fault to hide.' => 'Yazılımın kurulduğu sunucuda ürünün ihtiyaç duyduğu yetenekleri yoklar, bir kanıt kaydı oluşturur ve kısıtlı çalışma planını yazdırır: o sunucuda hangi özellikler kısıtlı çalışır, hangileri hiç çalışmaz. Eksik yetenek bir hata yerine planlı kısıt olarak bildirilir; çünkü o yeteneğe sahip olmayan sunucu gizlenecek bir kusur değil, belirtilecek bir olgudur.',
        'The results of those commands, published here' => 'Bu komutların burada yayımlanan sonuçları',
        'This page names what each command measures. It does not print what they returned on any particular installation, for the same reason the backup section does not: a result with no date on it is read as a permanent property, and it is not one.' => 'Bu sayfa her komutun neyi ölçtüğünü belirtir. Yedekleme bölümündeki gerekçeyle, belirli bir kurulumdaki sonuçlarını yazdırmaz: tarihsiz bir sonuç kalıcı bir özellik gibi okunur, oysa değildir.',
        'Questions this page cannot answer' => 'Bu sayfanın yanıtlayamadığı sorular',
        'Three things are decided by a person, not by this page, and each of them is worth settling before you subscribe rather than after: an availability commitment with a figure in it, a data processing agreement signed with your own organisation named in it, and any certificate or audit report your procurement process requires.' => 'Üç konuya bu sayfa değil bir kişi karar verir ve her biri abonelikten önce netleştirilmelidir: rakam içeren bir kullanılabilirlik taahhüdü, kuruluşunuzun adıyla imzalanmış veri işleme sözleşmesi ve satın alma sürecinizin gerektirdiği sertifika veya denetim raporları.',
        'The identity of the seller — the legal entity, the registered address and the tax details — is on the About page at /about, drawn from the same configuration as the contracts. The way to ask any of the above is the contact form at /contact, which stores your message and gives you a reference to quote.' => 'Satıcının kimliği — tüzel kişi, kayıtlı adres ve vergi bilgileri — sözleşmelerle aynı yapılandırmadan alınarak /about adresindeki Hakkımızda sayfasında gösterilir. Yukarıdaki konuları /contact adresindeki iletişim formundan sorabilirsiniz; form mesajınızı saklar ve sonraki yazışmalarda belirtebileceğiniz bir referans verir.',
        'What this statement says, and what it refuses to say' => 'Bu beyan ne söylüyor, neyi söylemeyi reddediyor?',
        'This statement is split three ways on purpose: what is measured and by which gate, what is known to be wrong, and what has not been measured at all. Anything in the third group is unknown. It is not "probably fine", and this page will not describe it that way.' => 'Bu beyan bilerek üçe ayrılmıştır: hangi kontrolle neyin ölçüldüğü, bilinen kusurlar ve hiç ölçülmeyenler. Üçüncü gruptaki her şey bilinmiyor demektir. “Muhtemelen sorunsuz” değildir ve sayfa böyle tanımlamaz.',
        'Every measured line below names the file or the command that measures it. This software is open source: you can read the gate and run it yourself rather than take the line on trust.' => 'Aşağıdaki her ölçülen satır, ölçümü yapan dosyayı veya komutu belirtir. Yazılım açık kaynaklıdır: satıra güvenmek yerine kontrolü okuyabilir ve kendiniz çalıştırabilirsiniz.',
        'A conformance claim against an accessibility standard' => 'Bir erişilebilirlik standardına uygunluk iddiası',
        'None is made here. A sentence such as "WCAG 2.1 AA compliant" means that the whole product has been audited against that standard by someone qualified to do it, and recorded. That has not happened for this service. Writing it anyway is the most common untruth on pages of this kind, and it is the one thing this page exists to avoid.' => 'Burada böyle bir iddia yoktur. “WCAG 2.1 AA uyumlu” gibi bir cümle, ürünün tamamının yetkin biri tarafından o standarda göre denetlendiği ve kayda geçirildiği anlamına gelir. Bu hizmet için böyle bir denetim yapılmadı. Yine de bunu yazmak, bu tür sayfalardaki en yaygın yanlış beyandır; bu sayfanın varlık nedeni tam da bundan kaçınmaktır.',
        'What is measured, and by which gate' => 'Ne ölçülüyor ve hangi kontrolle?',
        'These run against a real layout engine or a real browser, not a simulated one. That distinction matters: the repository\'s unit tests run in an environment that computes no layout at all, where no box has a height, nothing overflows and no touch target can be measured. Questions about size and overflow cannot be asked there and this statement does not pretend they were.' => 'Bunlar benzetimde değil, gerçek düzen motorunda veya tarayıcıda çalışır. Ayrım önemlidir: deponun birim testleri düzen hesaplamayan bir ortamda çalışır; hiçbir kutunun yüksekliği yoktur, hiçbir şey taşmaz ve dokunma hedefi ölçülemez. Boyut ve taşma soruları orada ölçülemez; bu beyan ölçülmüş gibi davranmaz.',
        'Touch target size, horizontal overflow and clipping on a narrow screen' => 'Dar ekranda dokunma hedefi boyutu, yatay taşma ve kırpılma',
        'Pages are opened in a real browser at 320 by 480 and again at wider sizes, and checked for: horizontal overflow, any interactive element clipped past the edge, touch targets smaller than 44 by 44, neighbouring targets closer than 8 pixels apart, silently truncated text, and content squeezed into a narrow strip by nested padding. The same run is repeated with the layout reversed, for the two supported languages that read right to left. Every interface component is measured this way on every change; the assembled corporate pages are measured with the same tool when they change, which is not the same thing and is why it is said here rather than rounded up.' => 'Sayfalar gerçek tarayıcıda 320 × 480 ve daha geniş boyutlarda açılır. Yatay taşma, kenardan kırpılan etkileşimli öğeler, 44 × 44 altındaki dokunma hedefleri, aralarında 8 pikselden az mesafe olan komşu hedefler, sessizce kesilen metinler ve iç içe dolguların dar bir şeride sıkıştırdığı içerik kontrol edilir. Aynı koşu, sağdan sola yazılan iki desteklenen dil için düzen ters çevrilerek tekrarlanır. Her arayüz bileşeni her değişiklikte böyle ölçülür; birleşik kurumsal sayfalar ise değiştiklerinde aynı araçla ölçülür. Bunlar aynı şey değildir; bu yüzden fark burada açıkça belirtilir.',
        'Reduced motion — the rule' => 'Azaltılmış hareket — kural',
        'When the device asks for reduced motion, the page has to be complete rather than diminished: the same sections, the same links, the same headings, and nothing hidden behind an entrance animation. A gate reads the stylesheets and fails if any declaration that starts motion sits outside the reduced-motion guard, so a single forgotten line cannot slip through by looking harmless.' => 'Cihaz azaltılmış hareket istediğinde sayfa eksilmeden tam kalmalıdır: aynı bölümler, bağlantılar ve başlıklar bulunmalı, hiçbir içerik giriş animasyonunun arkasında gizlenmemelidir. Bir kontrol stil dosyalarını okur ve hareket başlatan bir bildirim azaltılmış hareket korumasının dışındaysa başarısız olur; böylece unutulmuş tek bir satır zararsız görünerek geçemez.',
        'Reduced motion, increased contrast and forced colours — visual signatures' => 'Azaltılmış hareket, artırılmış kontrast ve zorunlu renkler — görsel imzalar',
        'The visual gate captures selected pages and display states in a browser, with screenshots 900 milliseconds apart. It compares coarse 16×12 brightness signatures: static checks fail when signature movement exceeds zero, while reference comparisons allow a 12/255 difference. These checks detect some motion and visual regressions; they do not compare every pixel or prove that every accessibility requirement is met.' => 'Görsel kontrol, seçili sayfaları ve görüntüleme durumlarını tarayıcıda 900 milisaniye arayla görüntüler. Kaba 16×12 parlaklık imzalarını karşılaştırır: statik kontrollerde imza hareketi sıfırı aşarsa kontrol başarısız olur; referans karşılaştırmalarında 12/255 farka izin verilir. Bu kontroller bazı hareket ve görsel regresyonları saptar; her pikseli karşılaştırmaz veya tam erişilebilirlik uyumunu kanıtlamaz.',
        'Text contrast in the corporate palette' => 'Kurumsal palette metin kontrastı',
        'Configured palette pairs are computed from the stylesheet and checked against their specified minimum ratios, including 7:1 for the configured body-text pairs. This does not cover every rendered combination or every local desktop colour token. Semi-transparent colours depend on the background behind them and are not covered by these opaque-token checks.' => 'Yapılandırılmış palet çiftleri stil dosyasından hesaplanıp belirlenen asgari oranlara göre kontrol edilir; yapılandırılmış gövde metni çiftleri için bu oran 7:1’dir. Bu, ekranda oluşan her renk birleşimini veya masaüstüne özel her yerel renk değişkenini kapsamaz. Yarı saydam renkler arkalarındaki zemine bağlıdır ve bu opak renk değişkeni kontrollerinin kapsamında değildir.',
        'Right-to-left layout' => 'Sağdan sola düzen',
        'Two of the nine languages the software supports are written right to left, and every physical direction in a stylesheet is reversed for them: a left padding lands at the end of the sentence rather than the start. A gate scans the stylesheets, the templates and the help articles for physical direction properties and classes, and requires the logical equivalents instead.' => 'Yazılımın desteklediği dokuz dilden ikisi sağdan sola yazılır ve stil dosyasındaki her fiziksel yön bu diller için ters çevrilir: sol dolgu, cümlenin başı yerine sonuna gelir. Bir kontrol stil dosyalarını, şablonları ve yardım yazılarını fiziksel yön özellikleri ve sınıfları için tarar; bunların yerine mantıksal karşılıklarını zorunlu tutar.',
        'Roles, names and keyboard behaviour of the interface components' => 'Arayüz bileşenlerinin rolleri, adları ve klavye davranışı',
        'Every story of every catalogue component is rendered and run through an accessibility rule engine, and the build fails on any violation. Colour contrast is switched off in that run and measured separately at token level, because the environment it runs in computes no colour.' => 'Katalogdaki her bileşenin her senaryosu çizilir ve erişilebilirlik kural motorundan geçirilir; herhangi bir ihlal derlemeyi başarısız kılar. Ortam renk hesaplamadığından bu koşuda renk kontrastı kapalıdır ve jeton düzeyinde ayrıca ölçülür.',
        'Minimum touch target in the component catalogue' => 'Bileşen kataloğunda asgari dokunma hedefi',
        'A separate contract holds the interface components to the 44 by 44 minimum, so a control does not fall below it between the browser measurements.' => 'Ayrı bir sözleşme arayüz bileşenlerini 44 × 44 asgari boyutta tutar; böylece tarayıcı ölçümleri arasında bir kontrol bu sınırın altına düşmez.',
        'What is known to be wrong' => 'Bilinen kusurlar',
        'These are measured findings that are still open. They are listed with the same weight as the measured lines above, because a gap that is only recorded in an internal file is a gap the reader never learns about.' => 'Bunlar ölçülmüş ve henüz kapanmamış bulgulardır. Yukarıdaki ölçülen satırlarla aynı ağırlıkta listelenir; çünkü yalnızca iç dosyada kayıtlı bir eksiklikten okuyucu haberdar olmaz.',
        'Links inside a sentence are smaller than 44 by 44' => 'Cümle içindeki bağlantılar 44 × 44 boyutundan küçüktür',
        'Links written into the middle of a sentence are the height of the line of text they sit in rather than 44 pixels: "Contact us" in the shared block that shows the plans, which appears on every page carrying that block, and "Write to us" on the help page. Making them 44 pixels tall would break the paragraph they are part of. The finding is left open and named here rather than closed by a rule that hides it — and it is written as a shape rather than a list of pages, because a list would be out of date the next time that block appears somewhere new.' => 'Cümle ortasındaki bağlantılar 44 piksel değil, içinde bulundukları metin satırı kadar yüksektir: planları gösteren ortak bloktaki “Bize ulaşın” bağlantısı bu bloğu kullanan her sayfada; “Bize yazın” bağlantısı ise yardım sayfasında bulunur. Bunları 44 piksel yapmak ait oldukları paragrafı bozardı. Bulgu, onu gizleyen bir kuralla kapatılmak yerine açık bırakılıp burada adlandırılır. Sayfa listesi yerine biçim olarak tanımlanır; çünkü blok yeni bir yerde kullanıldığında sayfa listesi eskirdi.',
        'Two links sit closer together than the minimum gap' => 'İki bağlantının arası asgari mesafeden kısadır',
        'On the pricing page, two neighbouring links are 7 pixels apart on a narrow screen where the minimum is 8. Seven pixels rather than eight is a small number, and it is written here for the same reason the larger gaps are: a threshold that is quietly rounded down once is a threshold that stops being one.' => 'Fiyat sayfasında dar ekrandaki iki komşu bağlantının arası, asgari 8 piksel yerine 7 pikseldir. Sekiz yerine yedi küçük bir farktır; daha büyük eksikliklerle aynı nedenle burada yazılıdır: bir kez sessizce aşağı yuvarlanan eşik, eşik olmaktan çıkar.',
        'Small targets frozen in the component catalogue' => 'Bileşen kataloğunda kayda alınmış küçük hedefler',
        'A checkbox control and a text link in the component catalogue are recorded as below the minimum, together with some layouts that waste horizontal space on a narrow screen. They are held in a baseline file so the count can only go down, never up — but they are debt, and the baseline is a record of debt rather than a pass.' => 'Bileşen kataloğunda bir onay kutusu kontrolü ve bir metin bağlantısı asgari boyutun altında kaydedilmiştir; dar ekranda yatay alanı boşa harcayan bazı düzenler de vardır. Sayı yalnızca azalsın, artmasın diye bir referans dosyasında tutulurlar. Ancak bunlar borçtur; referans dosyası başarı değil, borç kaydıdır.',
        'Limits of automated coverage' => 'Otomatik kontrol kapsamının sınırları',
        'The CI workflow runs the scene visual gate for selected pages and states, alongside automated checks, the logical-direction scan and component catalogue checks. That coverage is bounded: it does not exercise every page, every browser or every user journey, and a passing run does not prove that all visual or accessibility defects are absent.' => 'CI iş akışı, otomatik kontroller, mantıksal yön taraması ve bileşen kataloğu kontrolleriyle birlikte seçili sayfa ve durumlarda sahne görsel kontrolünü çalıştırır. Kapsam sınırlıdır: her sayfa, her tarayıcı veya her kullanıcı yolculuğu sınanmaz; başarılı bir çalıştırma bütün görsel veya erişilebilirlik kusurlarının bulunmadığını kanıtlamaz.',
        'What has not been measured' => 'Ölçülmeyenler',
        'Nothing in this section should be read as working. It should be read as unknown.' => 'Bu bölümde hiçbir şey çalışıyor diye okunmamalıdır. Bilinmiyor diye okunmalıdır.',
        'Use with a screen reader by a person who uses one' => 'Ekran okuyucu kullanan bir kişinin ekran okuyucuyla kullanımı',
        'No session with a screen reader user has been run against this service. Automated rule engines check the parts of a screen reader experience that a machine can see — that a control has a name, a role and a reachable label. They do not check whether the resulting page is usable, and nothing here has checked that.' => 'Bu hizmet üzerinde ekran okuyucu kullanıcısıyla bir oturum yapılmadı. Otomatik kural motorları, deneyimin makinenin görebildiği kısmını denetler: kontrolün adı, rolü ve erişilebilir etiketi bulunması gibi. Ortaya çıkan sayfanın kullanılabilir olup olmadığını denetlemezler; burada bunu denetleyen başka bir şey de yoktur.',
        'Every browser measurement behind this page was taken in one browser engine, on one machine, and there is no Apple device in that setup. Several things this interface relies on behave differently there. Nobody has looked, so the answer is unknown rather than likely.' => 'Bu sayfanın dayandığı tüm tarayıcı ölçümleri tek makinede, tek tarayıcı motoruyla alındı ve bu düzende Apple cihazı yoktur. Arayüzün dayandığı bazı özellikler orada farklı davranır. Kimse bakmadığı için yanıt olasılık değil, bilinmiyordur.',
        'Speech input, switch access and screen magnification' => 'Sesle giriş, anahtar erişimi ve ekran büyütme',
        'None of these has been exercised against this service.' => 'Bunların hiçbiri bu hizmet üzerinde denenmedi.',
        'The rest of the corporate site' => 'Kurumsal sitenin geri kalanı',
        'The browser measurements cover the pages that are published today. The site map holds several hundred further addresses that are written but not published; none of them has been measured, and none of them is reachable, so this statement covers what you can actually open and says nothing about the rest.' => 'Tarayıcı ölçümleri bugün yayımlanmış sayfaları kapsar. Site haritasında yazılmış ama yayımlanmamış yüzlerce başka adres vardır; hiçbiri ölçülmedi ve hiçbiri erişilebilir değildir. Bu beyan yalnızca gerçekten açabildiğiniz sayfaları kapsar, geri kalanı hakkında bir şey söylemez.',
        'The workspace application and the guest menu' => 'Çalışma alanı uygulaması ve misafir menüsü',
        'The component catalogue behind those screens is measured, component by component. The assembled screens are not measured as whole pages in a real browser the way the corporate pages are. A page can fail where none of its parts does.' => 'Bu ekranların arkasındaki bileşen kataloğu, bileşen bileşen ölçülür. Birleştirilmiş ekranlar, kurumsal sayfalar gibi gerçek tarayıcıda bütün sayfa olarak ölçülmez. Parçalarının hiçbiri kusurlu olmasa da sayfa kusurlu olabilir.',
        'How to report something' => 'Bir sorun nasıl bildirilir?',
        'Use the contact form at /contact. It needs no account, because somebody who cannot use the interface may not be able to sign in to report that. It stores the message and gives you a reference to quote. If the form itself is the thing that is broken for you, the seller\'s e-mail address is on the About page at /about.' => '/contact adresindeki iletişim formunu kullanın. Arayüzü kullanamayan biri sorunu bildirmek için oturum da açamayabileceğinden hesap gerekmez. Form mesajı saklar ve sonraki yazışmalarda belirtebileceğiniz bir referans verir. Sorun formun kendisindeyse satıcının e-posta adresi /about adresindeki Hakkımızda sayfasındadır.',
        'How quickly you are answered' => 'Ne kadar sürede yanıt alırsınız?',
        'No support response time is committed by this service, so this statement does not promise one. A phrase such as "as soon as possible" would be a promise nobody made, and it is left out for the same reason the availability figure is.' => 'Bu hizmet destek yanıt süresi taahhüt etmediğinden bu beyan da süre sözü vermez. “En kısa sürede” gibi bir ifade kimsenin vermediği bir söz olurdu; kullanılabilirlik rakamıyla aynı nedenle metne alınmaz.',
        'The one timing this service does commit to' => 'Bu hizmetin taahhüt ettiği tek süre',
        'The incident notification time has not been entered for this installation, so there is no committed timing to point at here either.' => 'Bu kurulum için olay bildirim süresi girilmediğinden burada gösterilebilecek bir süre taahhüdü de yoktur.',
        'Tell us what is broken' => 'Neyin çalışmadığını bize bildirin',
        'A report that names the page, the device and what happened is worth more than any gate on this list, because the gates only measure what somebody thought to measure.' => 'Sayfayı, cihazı ve ne olduğunu belirten bir bildirim, bu listedeki her kontrolden daha değerlidir; çünkü kontroller yalnızca birinin ölçmeyi düşündüğü şeyleri ölçer.',
    ];

    public static function availability(string $percent, string $source): string
    {
        return 'Hizmet Seviyesi Koşulları, takvim ayı başına %'.$percent.' kullanılabilirlik taahhüt eder; ölçüm kaynağı: '.$source.'.';
    }

    public static function incident(int $minutes): string
    {
        return 'İşletmeci hizmetin kullanılamadığını öğrendikten sonra, etkilenen müşterilere '.$minutes.' dakika içinde hesaplarındaki e-posta adresine bildirim yapılır. Herkese açık uç nokta gözlemleri https://zabuno.github.io/status/ adresinden kontrol edilebilir; bu gözlemler bildirim süresine uyulup uyulmadığını ölçmez.';
    }

    public static function support(int $hours): string
    {
        return 'Destek '.$hours.' saat içinde yanıt verir. Bu taahhüt bu kurulum için belirlenmiştir; iletişim sayfasında ve aldığınız alındı e-postasında gösterilen süreyle aynıdır.';
    }

    public static function accessibilityIncident(int $minutes): string
    {
        return 'Hizmet kullanılamadığında, işletmeci bunu öğrendikten sonra etkilenen müşterilere '.$minutes.' dakika içinde bildirim yapılır. Bu, bir kesintiye ilişkin taahhüttür; bu beyan onu erişilebilirlik bildirimlerini de kapsayacak şekilde genişletmez. Bunlar farklı sorun türleridir; aksini söylemek, başka bir konu için verilmiş bir sözü buraya taşımak olurdu.';
    }

    public static function text(string $english): string
    {
        return self::TEXT[$english] ?? throw new LogicException('Missing Turkish assurance text: '.$english);
    }
}
